### PR TITLE
Error template

### PR DESCRIPTION
**Pull request by brianteeman**
This PR creates a real error page for the template. It didnt exist before as it was just a copy of protostar with a hardcoded redirect at the top. This way the analytics and statistics will be recorded correctly

### CODE REVIEW

**Review by conconnl — APPROVED** [review]

**Comment by conconnl** [comment]
Implemented it and this is the result:
https://www.opensourcematters.org/bla

**Comment by brianteeman** [comment]
Thanks for merging. Wasn't hard to create ;)

**Comment by conconnl** [comment]
Maybe for you but following the J! Documentation, doesn't result in this.
Thanks for the effort, I did some additional tweaks.

https://github.com/joomla/opensourcematters.org/commit/c49c1433e476a6568a9c079b2c0ae63c459d565a
https://github.com/joomla/opensourcematters.org/commit/34afbd6c40cef5e03c063b8806fc836c3559976f
https://github.com/joomla/opensourcematters.org/commit/7c825b63596f081af872a047086b4825389075c9
https://github.com/joomla/opensourcematters.org/commit/ec349254c325d70116fa918b9497a593c4c245b4

**Comment by brianteeman** [comment]
Which documentation was wrong

**Comment by conconnl** [comment]
The one I mentioned in the issue:
https://github.com/joomla/joomla-websites/issues/1413

https://docs.joomla.org/Custom_error_pages

**Pull request merged**
